[project]
name = "pmrseedgen"
version="2023.11.20"

[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
    "cython"
]
build-backend = "setuptools.build_meta"

dependencies = [
    "peewee==3.14.4",
    "pyyaml",
    "firebase-admin==5.2.0"
]

[tool.setuptools]
packages = ["db", "maps", "maps.graph_edges", "maps.links", "metadata", "models", "models.options", "rando_enums",
    "rando_modules", ]

