[project]
name = "pmrseedgen"
version="2023.11.20"
dependencies = [
    "peewee==3.14.4",
    "pyyaml",
    "firebase-admin==5.2.0"
]

[tool.setuptools]
packages = ["db", "maps", "maps.graph_edges", "maps.links", "metadata", "models", "models.options", "rando_enums",
    "rando_modules", ]